kind: pipeline
name: default

steps:
- name: install
  image: node:11-alpine
  commands:
  - apk add python make g++
  - npm install
  when:
    branch:
      - infra
    event:
      - tag

- name: build
  image: node:11-alpine
  commands:
  - npm run build
  - echo ${DRONE_TAG}
  when:
    branch:
      - infra
    event:
      - tag

- name: make zip folder
  image: node:11-alpine
  commands:
  - apk add zip
  - cp -R ./dist ./axentix-v0.1.2-alpha
  - cp CHANGELOG.md ./axentix-v0.1.2-alpha/CHANGELOG.md
  - cp LICENSE ./axentix-v0.1.2-alpha/LICENSE
  - cp README.md ./axentix-v0.1.2-alpha/README.md
  - zip -r ./axentix-v0.1.2-alpha.zip ./axentix-v0.1.2-alpha
  when:
    branch:
      - infra
    event:
      - tag

- name: github release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_auth
    files:
      - axentix-v0.1.2-alpha.zip
    draft: true
    overwrite: true
  when:
    branch:
      - infra
    event:
      - tag