kind: pipeline
name: default

steps:
- name: Install
  image: node:11-alpine
  commands:
  - apk add python make g++
  - npm install
  when:
    branch:
      - infra
    event:
      - tag

- name: Build
  image: node:11-alpine
  commands:
  - npm run build
  when:
    branch:
      - infra
    event:
      - tag

- name: Github Release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_auth
    files:
      - dist/**/*
      - CHANGELOG.md
      - LICENSE
      - README.md
    draft: true
  when:
    branch:
      - infra
    event:
      - tag