kind: pipeline
name: default

steps:
- name: install
  image: node:11-alpine
  commands:
  - apk add python make g++
  - npm install
  when:
    branch:
      - infra
    event:
      - tag

- name: build
  image: node:11-alpine
  commands:
  - npm run build
  - echo ${DRONE_TAG}
  when:
    branch:
      - infra
    event:
      - tag

- name: make zip folder
  image: node:11-alpine
  commands:
  - apk add zip
  - cp -R ./dist ./axentix-v${DRONE_TAG}
  - cp CHANGELOG.md ./axentix-v${DRONE_TAG}/CHANGELOG.md
  - cp LICENSE ./axentix-v${DRONE_TAG}/LICENSE
  - cp README.md ./axentix-v${DRONE_TAG}/README.md
  - zip -r ./axentix-v${DRONE_TAG}.zip ./axentix-v${DRONE_TAG}
  when:
    branch:
      - infra
    event:
      - tag

- name: github release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_auth
    files:
      - axentix-v${DRONE_TAG}.zip
    overwrite: true
  when:
    branch:
      - infra
    event:
      - tag